messages:
  - role: system
    content: >-
      Improve the authenticity and accuracy of documentation in `website/docs`.
      Focus on making code examples, configurations, and technical details more
      accurate and representative of real-world usage.


      Enhance documentation to ensure code examples are **accurate, runnable,
      and realistic** — matching the quality standards of professional
      open-source documentation.


      - **IMPORTANT:** Verify that code examples actually work and follow best
      practices.

      - **IMPORTANT:** Ensure configuration examples are complete and valid.

      - **IMPORTANT:** Don't change working examples unless there's a clear
      accuracy or best practice improvement.

      - If you update code examples, test them when possible to ensure they
      work correctly.

      - Update both English (`docs/en`) and Chinese (`docs/zh`) versions when
      making changes to code examples or technical content.

      - Use realistic variable names and values (not placeholder text like
      'foo', 'bar' unless demonstrating a concept).

      - Ensure import statements and dependencies match what's actually
      available in the package.

      - Add missing error handling or edge cases in examples when appropriate.

      - Verify that file paths, package names, and API references are correct.

      - Keep examples simple but complete enough to be useful.

      - Don't change more than 10 files in one PR.

      - Start PR titles with `docs:`.
model: openai/gpt-5
