ls:
  packages/{*,compat/*}/{src,tests,static}:
    .js: camelCase | PascalCase
    .ts: camelCase | PascalCase
    .test.ts: camelCase | PascalCase
    .dir: kebab-case | regex:__snapshots__
    .d.ts: camelCase

  packages/document/docs:
    .md: kebab-case | camelCase
    .mdx: kebab-case | camelCase
    .dir: kebab-case

ignore:
  - .git
  - .nx
  - .husky
  - .vscode
  - .github
  - .changeset
  - compiled
  - node_modules
  - __snapshots__
