ls:
  # .dir: kebab-case
  packages/{*,compat/*}/src:
    .js: camelCase
    .ts: camelCase | PascalCase
    .d.ts: camelCase

ignore:
  - .git
  - .nx
  - .husky
  - .vscode
  - .github
  - .changeset
  - compiled
  - node_modules
