packages:
  - website
  - e2e/**
  - scripts/**
  - packages/**
  - examples/**
  - '!**/compiled/**'
  - '!**/dist/**'
  - '!**/dist-*/**'
  - '!**/create-rsbuild/template-*/**'
  - '!**/test-temp-*/**'

hoistPattern: []

patchedDependencies:
  css-loader@7.1.2: patches/css-loader@7.1.2.patch
  file-loader: patches/file-loader@6.2.0.patch
  http-proxy@1.18.1: patches/http-proxy@1.18.1.patch
  postcss-loader@8.2.0: patches/postcss-loader@8.2.0.patch
  url-loader: patches/url-loader@4.1.1.patch

strictPeerDependencies: false
engineStrict: true
trustPolicy: no-downgrade
trustPolicyExclude:
  # For ecosystem CI and Renovate
  - semver@5.7.2 || 6.3.1
  - chokidar@4.0.3
  - rxjs@7.8.2
  - '@modern-js/node-bundle-require@2.68.2'
  - '@modern-js/utils@2.68.2'
  - 'ua-parser-js@1.0.41'
