packages:
  - website
  - e2e/**
  - scripts/**
  - packages/**
  - examples/**
  - '!**/compiled/**'
  - '!**/dist/**'
  - '!**/dist-*/**'
  - '!**/create-rsbuild/template-*/**'
  - '!**/test-temp-*/**'
  - '!**/_node_modules/**'

engineStrict: true

hoistPattern: []

dedupePeers: true

patchedDependencies:
  css-loader@7.1.4: patches/css-loader@7.1.4.patch
  postcss-loader@8.2.1: patches/postcss-loader@8.2.1.patch

strictPeerDependencies: false

allowBuilds:
  '@parcel/watcher': true
  core-js: false
  simple-git-hooks: false
  svelte-preprocess: false

minimumReleaseAgeExclude:
  - '@rspack/*'
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rspress/*'
  - '@rstest/*'
  - '@rsdoctor/*'
  - '@rslint/*'
