(()=>{"use strict";var e={261:e=>{
/*!
 * ee-first
 * Copyright(c) 2014 Jonathan Ong
 * MIT Licensed
 */
e.exports=first;function first(e,n){if(!Array.isArray(e))throw new TypeError("arg must be an array of [ee, events...] arrays");var r=[];for(var t=0;t<e.length;t++){var i=e[t];if(!Array.isArray(i)||i.length<2)throw new TypeError("each array member must be [ee, events...]");var o=i[0];for(var a=1;a<i.length;a++){var s=i[a];var u=listener(s,callback);o.on(s,u);r.push({ee:o,event:s,fn:u})}}function callback(){cleanup();n.apply(null,arguments)}function cleanup(){var e;for(var n=0;n<r.length;n++){e=r[n];e.ee.removeListener(e.event,e.fn)}}function thunk(e){n=e}thunk.cancel=cleanup;return thunk}function listener(e,n){return function onevent(r){var t=new Array(arguments.length);var i=this;var o=e==="error"?r:null;for(var a=0;a<t.length;a++){t[a]=arguments[a]}n(o,i,e,t)}}},772:(e,n,r)=>{
/*!
 * on-finished
 * Copyright(c) 2013 Jonathan Ong
 * Copyright(c) 2014 Douglas Christopher Wilson
 * MIT Licensed
 */
e.exports=onFinished;e.exports.isFinished=isFinished;var t=tryRequireAsyncHooks();var i=r(261);var o=typeof setImmediate==="function"?setImmediate:function(e){process.nextTick(e.bind.apply(e,arguments))};function onFinished(e,n){if(isFinished(e)!==false){o(n,null,e);return e}attachListener(e,wrap(n));return e}function isFinished(e){var n=e.socket;if(typeof e.finished==="boolean"){return Boolean(e.finished||n&&!n.writable)}if(typeof e.complete==="boolean"){return Boolean(e.upgrade||!n||!n.readable||e.complete&&!e.readable)}return undefined}function attachFinishedListener(e,n){var r;var t;var o=false;function onFinish(e){r.cancel();t.cancel();o=true;n(e)}r=t=i([[e,"end","finish"]],onFinish);function onSocket(n){e.removeListener("socket",onSocket);if(o)return;if(r!==t)return;t=i([[n,"error","close"]],onFinish)}if(e.socket){onSocket(e.socket);return}e.on("socket",onSocket);if(e.socket===undefined){patchAssignSocket(e,onSocket)}}function attachListener(e,n){var r=e.__onFinished;if(!r||!r.queue){r=e.__onFinished=createListener(e);attachFinishedListener(e,r)}r.queue.push(n)}function createListener(e){function listener(n){if(e.__onFinished===listener)e.__onFinished=null;if(!listener.queue)return;var r=listener.queue;listener.queue=null;for(var t=0;t<r.length;t++){r[t](n,e)}}listener.queue=[];return listener}function patchAssignSocket(e,n){var r=e.assignSocket;if(typeof r!=="function")return;e.assignSocket=function _assignSocket(e){r.call(this,e);n(e)}}function tryRequireAsyncHooks(){try{return r(852)}catch(e){return{}}}function wrap(e){var n;if(t.AsyncResource){n=new t.AsyncResource(e.name||"bound-anonymous-fn")}if(!n||!n.runInAsyncScope){return e}return n.runInAsyncScope.bind(n,e,null)}},852:e=>{e.exports=require("async_hooks")}};var n={};function __nccwpck_require__(r){var t=n[r];if(t!==undefined){return t.exports}var i=n[r]={exports:{}};var o=true;try{e[r](i,i.exports,__nccwpck_require__);o=false}finally{if(o)delete n[r]}return i.exports}if(typeof __nccwpck_require__!=="undefined")__nccwpck_require__.ab=__dirname+"/";var r=__nccwpck_require__(772);module.exports=r})();