name: Check Changeset

on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 1

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      -  name: Check Changeset
         run: pnpm run check-changeset
