name: Release Nightly

on:
  workflow_dispatch:
  # schedule:
    # 00:00 AM Beijing Time.
    # - cron: "0 16 * * *"

permissions:
  id-token: write

jobs:
  release:
    name: Release Nightly
    if: github.repository == 'web-infra-dev/rsbuild'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Release
        uses: web-infra-dev/actions@v2
        with:
          version: nightly
          branch: main
          type: 'release'
          tools: 'changeset'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
